### ISSUE TITLE
portaudio/info.rkt version should also be updated

### ISSUE THREAD

**Issue by cwebber** [jbclements/portaudio#10]
018e7c9f1049aa301a3d03dc8faa48484782d1d5 changed the version number in toplevel info.rkt, but in order to get rsound working I also needed to change portaudio/info.rkt

Should there really be two separate version numbers or info files to maintain anyway?

**Comment by jbclements** [comment]
I was unable to duplicate this; specifically, I just installed rsound on a fresh installation using "racocs pkg install --auto rsound", and it finished without error. It seems unlikely that the package dependency would depend on the version of the individual collections. Actually, though, I don't think the inner one should have a "version" at all. I'm going to remove it.

**Comment by jbclements** [comment]
okay, done. Closing, but feel free to re-open if I've misunderstood the underlying issue.

closed by #d1f41b1915e42a09868fbe979
