### ISSUE TITLE
Update portaudio dylib for os x.

### ISSUE THREAD

**Issue by LeifAndersen** [jbclements/portaudio#5]
The version of portaudio that this ships is old, and causes an error message like this to be printed:

 > 2018-06-13 11:05:23.781 DrRacket[12511:1288003] 11:05:23.781 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

It seems like the right thing to do here would be to update the dylib that portaudio ships with for os x.

**Comment by jbclements** [comment]
Done!

sigh.
